[package]
name = "engine-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
anyhow = { workspace = true }
engine-i18n = { path = "../engine-i18n" }
